"""
Backtesting: evaluate historical prediction accuracy, Brier score, calibration, and ROI.

Usage:
  python main.py backtest football
  python main.py backtest tennis
  python main.py backtest all

Results are generated by `python main.py train` and stored in data/backtest/*.json.
If no results exist yet, prompts the user to run training first.
"""
import json
from pathlib import Path

BACKTEST_DIR = Path(__file__).parent.parent / "data" / "backtest"


def load_results(sport: str) -> dict | None:
    path = BACKTEST_DIR / f"{sport}_results.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def _bar(fraction: float, width: int = 20, char: str = "█", empty: str = "░") -> str:
    filled = int(round(fraction * width))
    return char * filled + empty * (width - filled)


def _brier_skill_score(brier: float, naive_brier: float) -> float:
    """BSS = 1 - (BS / BS_naive). Positive = better than naive uniform forecast."""
    if naive_brier <= 0:
        return 0.0
    return round(1 - brier / naive_brier, 4)


def run_backtest(sport: str, console=None):
    """Load and display backtest results for a sport via Rich console."""
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
    from rich.text import Text
    from rich import box

    con = console or Console()

    results = load_results(sport)
    if results is None:
        con.print(
            Panel(
                Text.assemble(
                    (f"  No backtest results found for {sport}.\n\n", "yellow"),
                    ("  Run ", "dim"),
                    (f"python main.py train {sport}", "bold white"),
                    (" first.\n\n", "dim"),
                    ("  Training scrapes real match history and fits the Dixon-Coles model + ML ensemble.\n", "dim"),
                    ("  Typical runtime: 5–15 minutes (Understat scraping is rate-limited).", "dim"),
                ),
                title=f"[dim]Backtest — {sport}[/dim]",
                border_style="yellow",
                padding=(0, 1),
            )
        )
        return

    n_train = results.get("n_train", 0)
    n_test = results.get("n_test", 0)
    ml_acc = results.get("ml_accuracy")
    ml_brier = results.get("ml_brier")
    dc_acc = results.get("dc_accuracy")
    dc_brier = results.get("dc_brier")
    naive_brier = results.get("naive_brier", 0.667)
    generated_at = results.get("generated_at", "unknown")[:10]

    sport_title = sport.title()
    con.print()

    # ── Summary panel ─────────────────────────────────────────────────────────
    lines = []
    lines.append(f"  {'Training samples:':<28} {n_train:,}")
    lines.append(f"  {'Test samples (held-out 20%):':<28} {n_test:,}")
    lines.append(f"  {'Generated:':<28} {generated_at}")
    lines.append("")

    if ml_acc is not None:
        ml_bss = _brier_skill_score(ml_brier, naive_brier)
        ml_bss_str = f"{ml_bss:+.3f}"
        bss_color = "bright_green" if ml_bss > 0 else "red"
        lines.append(f"  {'ML Ensemble (RF+XGBoost)':<28}")
        lines.append(f"    Accuracy : {ml_acc:.1%}  {'[dim](argmax = correct outcome)[/dim]'}")
        lines.append(f"    Brier    : {ml_brier:.4f}  [dim](naive baseline {naive_brier:.3f})[/dim]")
        lines.append(f"    Skill    : [{bss_color}]{ml_bss_str}[/{bss_color}]  [dim](+ve = beats naive uniform)[/dim]")
        lines.append("")

    if dc_acc is not None:
        dc_bss = _brier_skill_score(dc_brier, naive_brier)
        dc_bss_str = f"{dc_bss:+.3f}"
        bss_color = "bright_green" if dc_bss > 0 else "red"
        lines.append(f"  {'Dixon-Coles (MLE-fitted)':<28}")
        lines.append(f"    Accuracy : {dc_acc:.1%}")
        lines.append(f"    Brier    : {dc_brier:.4f}  [dim](naive baseline {naive_brier:.3f})[/dim]")
        lines.append(f"    Skill    : [{bss_color}]{dc_bss_str}[/{bss_color}]")

    summary = "\n".join(lines)

    con.print(Panel(
        summary,
        title=f"[bold white]  {sport_title} Model Performance  —  Backtest Results[/bold white]",
        border_style="bright_blue",
        padding=(0, 1),
    ))

    # ── Calibration chart ─────────────────────────────────────────────────────
    calibration = results.get("calibration", [])
    if calibration:
        cal_table = Table(
            title=f"[dim]Calibration  (predicted probability vs. actual outcome frequency)[/dim]",
            box=box.SIMPLE,
            show_header=True,
            header_style="bold dim",
            padding=(0, 1),
            show_edge=False,
        )
        cal_table.add_column("Pred prob", style="dim", width=10)
        cal_table.add_column("Actual freq", width=12)
        cal_table.add_column("Count", justify="right", width=8)
        cal_table.add_column("Chart  (actual)", min_width=30)

        for row in calibration:
            pred = row["pred"]
            actual = row["actual"]
            count = row["count"]
            if count == 0:
                continue

            # Colour: green if within 5pp of perfect calibration, yellow ≤ 10pp, red beyond
            diff = abs(pred - actual)
            if diff < 0.05:
                color = "bright_green"
            elif diff < 0.10:
                color = "yellow"
            else:
                color = "red"

            bar_str = _bar(actual, width=24)
            cal_table.add_row(
                f"{pred:.0%}",
                f"[{color}]{actual:.0%}[/{color}]",
                str(count),
                f"[{color}]{bar_str}[/{color}]  {actual:.0%}",
            )

        con.print(cal_table)
        con.print(
            "  [dim]Perfect calibration: a 60% prediction is right 60% of the time. "
            "Green = within 5 pp. Red = miscalibrated.[/dim]\n"
        )

    # ── Interpretation guide ──────────────────────────────────────────────────
    con.print(Panel(
        Text.assemble(
            ("  What these numbers mean:\n\n", "bold dim"),
            ("  Brier Score  ", "white"), ("  Proper scoring rule (lower = better).\n", "dim"),
            ("                  ", "dim"), ("0.0 = perfect, 0.333 = 3-class naive, 0.5 = 2-class naive.\n\n", "dim"),
            ("  Brier Skill  ", "white"), ("  Improvement over naive uniform baseline.\n", "dim"),
            ("                  ", "dim"), ("+0.10 means model is 10% better than guessing equally.\n\n", "dim"),
            ("  Accuracy     ", "white"), ("  % of matches where argmax prediction = actual outcome.\n", "dim"),
            ("                  ", "dim"), ("Football 3-class random baseline = 33.3%.\n\n", "dim"),
            ("  Calibration  ", "white"), ("  For each predicted probability, how often is it right?\n", "dim"),
            ("                  ", "dim"), ("A well-calibrated model matches the diagonal perfectly.", "dim"),
        ),
        border_style="dim",
        padding=(0, 1),
    ))

    con.print(
        f"  [dim]Run [bold]python main.py train {sport}[/bold] to retrain with latest data.[/dim]\n"
    )


def run_all_backtests(console=None):
    """Show backtest reports for all sports that have results."""
    from rich.console import Console
    con = console or Console()

    sports = ["football", "tennis"]
    any_found = False
    for sport in sports:
        if load_results(sport) is not None:
            any_found = True
            run_backtest(sport, con)

    if not any_found:
        con.print(
            "\n  [yellow]No backtest results found. Run [bold]python main.py train[/bold] first.[/yellow]\n"
        )
